### ISSUE TITLE
mz-chip-input error

### ISSUE THREAD

**Issue by ronjohn83** [sherweb/ngx-materialize#306]
Uncaught TypeError: this.chipInputElement.material_chip is not a function
    at MzChipInputComponent.get [as value] (chip-input.component.js:17)
    at eval (chip-input.component.js:42)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2025)

**Comment by scote** [comment]
May you add a Stackblitz example to your issue please?

**Comment by ronjohn83** [comment]
I’m sorry but what is a stackblitz?

**Comment by jfcere** [comment]
Stackblitz is like Plunker or JsFiddle, it allows you to reproduce the problem in a live application so we can investigate.

Use this link: https://stackblitz.com/edit/ngx-materialize and send us the link of your problem reproduction.

**Comment by ronjohn83** [comment]
Here's another bug I'm having with a select. Was it too early to begin
using these controls? I've ran into a lot of problems implementing these
controls but i appreciate your help.

https://stackblitz.com/edit/ngx-materialize-vhrxhr

**Comment by jfcere** [comment]
Hi @ronjohn83,

#### Mz-Chip-Input stackblitz example
I fixed your example for `mz-chip-input` here: https://stackblitz.com/edit/ngx-materialize-ctddse

#### Uncaught TypeError: this.chipInputElement.material_chip is not a function
Concerning the error you mentioned, you need to be sure `jquery.min.js` is loaded **before** `materialize.min.js` ... the same problem was present in the stackblitz example.

Let me know if it anwers your question correctly.

**Comment by jfcere** [comment]
Just a "heads-up" ... I deleted your message about the select problem as you already post another issue for it.

**Comment by ronjohn83** [comment]
I copied your code exactly from stackblitz and I'm still getting the
following and yes I made sure jquery.min.js is loaded before
materialize.min.js.

core.js:1448 ERROR Error: Uncaught (in promise): TypeError:
this.chipInputElement.material_chip is not a function
TypeError: this.chipInputElement.material_chip is not a function
    at MzChipInputComponent.get [as value] (chip-input.component.js:17)
    at MzChipInputComponent.writeValue (chip-input.component.js:67)
    at eval (forms.js:2392)
    at eval (forms.js:3971)
    at Array.forEach (<anonymous>)
    at FormControl.setValue (forms.js:3971)
    at eval (forms.js:6255)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4749)
    at ZoneDelegate.invoke (zone.js:387)
    at MzChipInputComponent.get [as value] (chip-input.component.js:17)
    at MzChipInputComponent.writeValue (chip-input.component.js:67)
    at eval (forms.js:2392)
    at eval (forms.js:3971)
    at Array.forEach (<anonymous>)
    at FormControl.setValue (forms.js:3971)
    at eval (forms.js:6255)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4749)
    at ZoneDelegate.invoke (zone.js:387)
    at resolvePromise (zone.js:809)
    at eval (zone.js:861)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1517)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1543)

On Wed, Apr 4, 2018 at 6:57 PM, Jean-Francois Cere <notifications@github.com

**Comment by jfcere** [comment]
As I said ...

> you need to be sure jquery.min.js is loaded before materialize.min.js ... the same problem was present in the stackblitz example
